name: XClean Jobs

on:
  schedule:
    # Runs at 01:02 UTC on Fri
    - cron: '2 1 * * FRI'
  workflow_dispatch:
    inputs:
      days_old:
        description: "The amount of days old to delete"
        default: "3"
        required: false
env:
  SCHEDULED_DAYS_OLD: "4"

jobs:
  clean-logs:
    runs-on: ubuntu-22.04
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days_old: ${{ github.event.inputs.days_old || env.SCHEDULED_DAYS_OLD }}
